### PR TITLE
Frontend piece for stressed app

### PR DESCRIPTION
**Pull request by catalinmiron**
### todos
- [x] make chart responsive
- [x] create some logic for timeseries request ( since is now hardcoded )

cc: @mihneadb

### CODE REVIEW

**Comment by mihneadb** [comment]
@catalinmiron please add *.pyc to gitignore as well. I didn't include them in the repo gitignore because they are usually ignored globally.

**Comment by mihneadb** [comment]
You might be missing deps from the package.json file? I did `npm install` and then:

```
11:02:37 mihneab@mihneab-2.local static 1-create-frontend-for-stressed npm run-script build

> react-hot-boilerplate@1.0.0 build /Users/mihneab/localCode/uberVU/stressed/static
> webpack --config webpack.config.js --progress --profile --colors

24ms build modules
1ms seal
4ms optimize
7ms hashing
6ms create chunk assets
1ms additional chunk assets
0ms optimize chunk assets
1ms optimize assets
Hash: 9daefc80752187c411c2
Version: webpack 1.8.4
Time: 66ms
   [0] multi main 28 bytes {0} [built] [1 error]
       factory:0ms building:1ms = 1ms

ERROR in multi main
Module not found: Error: Cannot resolve module 'react-hot' in /Users/mihneab/localCode/uberVU/stressed/static
 @ multi main
```

**Comment by catalinmiron** [comment]
@mihneadb done! `*.pyc` is not working, dunno why :-1:  check now:

`npm run-script watch` or `npm run-script build`

**Comment by catalinmiron** [comment]
@mihneadb please take another look:

A little preview: 
stressed_app_v2

Todo: 
- [ ] make column chart responsive, add `flexbox` rows and columns

**Comment by mihneadb** [comment]
@catalinmiron try `git rm (possibly -f) *.pyc` and commit that as well. I think it will solve the problem.

Re: preview - SWEEEET! :D

**Comment by catalinmiron** [comment]
wdyt ? is this better ? 

stressed_app_

**Comment by catalinmiron** [comment]
@mihneadb i want to keep my local db :(

**Comment by mihneadb** [comment]
@catalinmiron that is in `data.db`, nothing to do with `.pyc` :).

**Comment by mihneadb** [comment]
I'm not sure what 's the difference between the two gifs. Other than 8/9 vs 13/14?

**Comment by catalinmiron** [comment]
> I'm not sure what 's the difference between the two gifs. Other than 8/9 vs 13/14?

The chart has a little `margin-right` to make the necessary room for navigation

**Comment by mihneadb** [comment]
Oh sorry. Yes, totally better with margin!

**Comment by mihneadb** [comment]
@catalinmiron let's merge something so we have a v0.0.1 :dancer:

**Comment by palcu** [comment]
I'm waiting to be a beta tester.

#stalker :bear:

**Comment by catalinmiron** [comment]
cc: @mihneadb

**Comment by catalinmiron** [comment]
Also, @mihneadb , if you have some time, please ensure that "Flask" router it's working. I want to use react-router, but when going to `/stats` and refresh, the app fails to load `stats` component.

Maybe you can do something like:

``` python
@app.route('/<path:p>')
def ui(p):
    return app.send_static_file('index.html')
```

or 

``` python
def index():
    pass
app.add_url_rule('/', 'index', index)
```

**Comment by mihneadb** [comment]
@catalinmiron works for me, gg. Let's merge this? :D

**Comment by mihneadb** [comment]
@catalinmiron btw - do we really need to keep the build (js, css) files in the repo?

**Comment by catalinmiron** [comment]
@mihneadb i'll enhance the build process, but for time being, we'll keep it like this.

**Pull request merged**
